apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notification-service
  labels:
    app: {{ .Release.Name }}-notification-service
spec:
  selector:
    app: {{ .Release.Name }}-notification-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP 